version: "3.7"  

services:
  postgresql:
    image: postgres:15.3
    volumes:
      - ./pg/data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "${DB_ROOT_USER}"
      POSTGRES_PASSWORD: "${DB_ROOT_PASSWORD}"
    ports:
      - "${DB_PORT}:5432"
